### PR TITLE
Add support for django 3.1

### PR DESCRIPTION
**Pull request by rsalmaso**
Add next django version (3.1), django master and python 3.8 to test matrix.
Update import of Context in helper.py

### CODE REVIEW

**Comment by yakky** [comment]
See https://github.com/divio/django-sekizai/pull/89#issuecomment-637186553

**Comment by rsalmaso** [comment]
Merge with (closed) #89

**Comment by yakky** [comment]
@FinalAngel is circle ci still useful? Its configuration must be completely rewritten, and I don't see a reason to keep both travis and circle ci active: what's your opinion?

**Comment by FinalAngel** [comment]
@yakky really not getting notifications with the new UI... I'm looking into it

**Comment by FinalAngel** [comment]
will be replaced by:
https://github.com/divio/django-sekizai/pull/92

@rsalmaso thank you very much! Any specific reason why you included:

```
setenv =
       PYTHONDONTWRITEBYTECODE=1
       PYTHONWARNINGS=once
```
?

**Comment by rsalmaso** [comment]
> Any specific reason why you included:
> 
> ```
> setenv =
>        PYTHONDONTWRITEBYTECODE=1
>        PYTHONWARNINGS=once
> ```
> 
> ?
Just preference

**Pull request closed without merging**
